### ISSUE TITLE
CONFIG_SIGNED_IMAGES and image hashing

### ISSUE THREAD

**Issue by michaelboulton** [sbabic/swupdate#17]
If you specify a sha256 hash for an image in sw-description and have signed images turned off, then running swupdate gives the error:

```
[NOTIFY] : SWUPDATE failed [1] Image invalid or corrupted. Not installing ...
```

This is because the interface to the hash functions in include/sslapi.h is disabled when CONFIG_SIGNED_IMAGES is turned off. I ran into this issue while just doing some testing, and I was just using the hash as a stronger way of detecting if the image was corrupted in transit and didn't want to bother signing and verifying the images. Hashing is not the same as signing, and I think this should have a different configuration variable, or just be on by default.

On a small but related note, the error message is misleading in this case - the image is not corrupt or invalid, it's that there is a hash mismatch.

**Comment by sbabic** [comment]
Hi Michael,

On 27/09/2016 13:38, michaelboulton wrote:
> If you specify a sha256 hash for an image in sw-description and have
> signed images turned off, then running swupdate gives the error:
> 
> |[NOTIFY] : SWUPDATE failed [1] Image invalid or corrupted. Not
> installing ... |
> 

I think I have already seen it or someone has already reported this
issue. sha256 are not supported if SIGNED_IMAGE is disable.

Anyway, this is just because I used it together to verify images. I
agree they are two distinct features, and sha256 can be used as stronger
checksum.

> This is because the interface to the hash functions in include/sslapi.h
> is disabled when CONFIG_SIGNED_IMAGES is turned off.

Yes, I see, confirmed.

> I ran into this
> issue while just doing some testing, and I was just using the hash as a
> stronger way of detecting if the image was corrupted in transit and
> didn't want to bother signing and verifying the images. Hashing is not
> the same as signing, and I think this should have a different
> configuration variable, or just be on by default.

If this is always on, the ssl library must be always linked, because I
am using the crypto functions. This increase the footprint and on some
devices where swupdate is used as rescue system is a problem.

> 
> On a small but related note, the error message is misleading in this
> case - the image is not corrupt or invalid, it's that there is a hash
> mismatch.

Agree, the output of the error should be changed to reflect the real error.

Best regards,
Stefano Babic


-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by sbabic** [comment]
Patch sent to ML to fix this
