### ISSUE TITLE
Files can be an archive type, but can not be extracted onto ubivolume

### ISSUE THREAD

**Issue by flar-developer** [sbabic/swupdate#25]
Hello, Stefano!

The files can be of type "archive", which have a very nice feature of extracting it on a mounted partition.
But it can not mount UBI volume by name.

I have successfully mounted UBI volume via it's device filename /dev/ubi0_0
```
files: (
    {
        filename = "kernel.tar.xz";
        path = "/";
        device = "/dev/ubi0_0";
        filesystem = "ubifs";
        type = "archive";
    }
);
```

It would be very helpfull to support mounting ubifs volumes by names.

Best regards,
Anton.

**Comment by sbabic** [comment]
Hi Anton,

On 16/12/2016 16:22, Anton wrote:
> Hello, Stefano!
> 
> The files can be of type "archive", which have a very nice feature of
> extracting it on a mounted partition.
> But it can not mount UBI volume by name.
> 

This is not supported.

> I have successfully mounted UBI volume via it's device filename /dev/ubi0_0
> 
> |files: ( { filename = "kernel.tar.xz"; path = "/"; device =
> "/dev/ubi0_0"; filesystem = "ubifs"; type = "archive"; } ); |
> 
> It would be very helpfull to support mounting ubifs volumes by names.
> 

Yes, it can be helpful : do you plan to implement it and send a patch ?

Best regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by sbabic** [comment]
Hi Anton,

please send your question to the ML, too - thanks !

On 16/12/2016 16:22, Anton wrote:
> Hello, Stefano!
> 
> The files can be of type "archive", which have a very nice feature of
> extracting it on a mounted partition.
> But it can not mount UBI volume by name.
> 

This is not supported.

> I have successfully mounted UBI volume via it's device filename /dev/ubi0_0
> 
> |files: ( { filename = "kernel.tar.xz"; path = "/"; device =
> "/dev/ubi0_0"; filesystem = "ubifs"; type = "archive"; } ); |
> 
> It would be very helpfull to support mounting ubifs volumes by names.
> 

Yes, it can be helpful : do you plan to implement it and send a patch ?

Best regards,
Stefano



-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by sbabic** [comment]
пятница, 16 декабря 2016 г., 18:38:25 UTC+3 пользователь Stefano Babic написал:
> Hi Anton,
> 
> please send your question to the ML, too - thanks !
> 
> On 16/12/2016 16:22, Anton wrote:
> > Hello, Stefano!
> > 
> > The files can be of type "archive", which have a very nice feature of
> > extracting it on a mounted partition.
> > But it can not mount UBI volume by name.
> > 
> 
> This is not supported.
May be that was not supposed to work, but currently on 2016.10 i have successfully used archive type via files.

> 
> > I have successfully mounted UBI volume via it's device filename /dev/ubi0_0
> > 
> > |files: ( { filename = "kernel.tar.xz"; path = "/"; device =
> > "/dev/ubi0_0"; filesystem = "ubifs"; type = "archive"; } ); |
> > 
> > It would be very helpfull to support mounting ubifs volumes by names.
> > 
> 
> Yes, it can be helpful : do you plan to implement it and send a patch ?
I would like to know if I should implement it via images? Then i will need to add parsing attributes "path" and "filesystem" for all images.

> Best regards, 
> Stefano 

Best regards,
Anton.

**Comment by sbabic** [comment]
Hi Anton,

On 17/12/2016 09:57, flar.developer@gmail.com wrote:
> пятница, 16 декабря 2016 г., 18:38:25 UTC+3 пользователь Stefano
> Babic написал:
>> Hi Anton,
>> 
>> please send your question to the ML, too - thanks !
>> 
>> On 16/12/2016 16:22, Anton wrote:
>>> Hello, Stefano!
>>> 
>>> The files can be of type "archive", which have a very nice
>>> feature of extracting it on a mounted partition. But it can not
>>> mount UBI volume by name.
>>> 
>> 
>> This is not supported.
> May be that was not supposed to work, but currently on 2016.10 i have
> successfully used archive type via files.
> 

Nice that it works even if it was not tested before. However, using
device with UBI has big limitations. It works if the order how the
devices are attached remains the same. Just after a small change, it
does not work anymore. I agree that this becomes reliable using volumes
instead of devices in case of UBI.

>> 
>>> I have successfully mounted UBI volume via it's device filename
>>> /dev/ubi0_0
>>> 
>>> |files: ( { filename = "kernel.tar.xz"; path = "/"; device = 
>>> "/dev/ubi0_0"; filesystem = "ubifs"; type = "archive"; } ); |
>>> 
>>> It would be very helpfull to support mounting ubifs volumes by
>>> names.
>>> 
>> 
>> Yes, it can be helpful : do you plan to implement it and send a
>> patch ?
> I would like to know if I should implement it via images?

Why using images ?

> Then i will
> need to add parsing attributes "path" and "filesystem" for all
> images.

It makes no sense. An image is filesystem unaware, and I am expecting
that an image is installed independently which is the filesystem that it
contains. The "archive" handler works with file-based and it is not
thought to work with images.

To add what you propose, I am expecting the following changes:

- "volume" is parsed for files, too, and value is stored in the list
(files / images are both "images" and contain the same shareholders).
- in the archive handler, it must be checked if "volume" is set in case
of "ubifs" filesystem. Because swupdate has already scanned the storages
on board, the handler must check if a volume with the same name was
found. The "device" can be still maintained for the case we have volumes
with the same name belonging to different MTD devices.
- after these checks, the archive handler mounts the UBI volume instead
of the device.

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================
